export const MY_MENU = [
  {
    id: "overnight-oats",
    name: "Overnight Oats",
    emoji: "🥣",
    category: "breakfast",
    summer: true,
    tags: ["no-cook", "prep-ahead"],
    cal: [250, 420], protein: [10, 16], carbs: [30, 55], fat: [10, 16], fiber: [8, 12],
    servingNote: "1 jar",
    ingredients: ["Oats (30–50g)", "Milk (30–45ml)", "Greek yoghurt (45–60g)", "Chia seeds (5–12g)", "Berries (30–60g)", "Dark chocolate chips (5–15g)", "Jam (optional, 10–45g)"],
    recipe: "Layer oats and milk in a jar. Add yoghurt and chia seeds. Mix. Top with berries and chocolate chips. Refrigerate overnight. Eat cold. Done.",
    cookTime: "5 min + overnight",
  },
  {
    id: "protein-shake",
    name: "Protein Shake",
    emoji: "🥤",
    category: "breakfast",
    summer: true,
    tags: ["no-cook", "quick"],
    cal: [136, 200], protein: [24, 30], carbs: [6, 15], fat: [1, 5], fiber: [1, 2],
    servingNote: "1 shaker",
    ingredients: ["Whey protein (35g)", "Water or milk (300ml)"],
    recipe: "Add protein powder to shaker. Add water or milk. Shake for 10 seconds. Drink. That's it.",
    cookTime: "1 min",
  },
  {
    id: "filter-coffee",
    name: "Filter Coffee",
    emoji: "☕",
    category: "drinks",
    summer: false,
    tags: ["drink"],
    cal: [90, 120], protein: [5, 5], carbs: [10, 10], fat: [5, 5], fiber: [0, 0],
    servingNote: "1 cup",
    ingredients: ["Coffee decoction", "Milk (150ml)", "Sugar or sweetener (optional)"],
    recipe: "Mix decoction and hot milk in the ratio you like. Add sweetener if using. The classic.",
    cookTime: "5 min",
  },
  {
    id: "tuna-yoghurt-bowl",
    name: "Tuna Yoghurt Bowl",
    emoji: "🐟",
    category: "protein-meals",
    summer: true,
    tags: ["high-protein", "no-cook"],
    cal: [250, 350], protein: [30, 40], carbs: [8, 12], fat: [5, 10], fiber: [1, 2],
    servingNote: "1 bowl",
    ingredients: ["Canned tuna (100–150g)", "Greek yoghurt (150–170g)", "Cucumber (100g)", "Garlic (2 cloves)", "Salt", "Pepper", "Cheese (optional, 10–20g)"],
    recipe: "Drain tuna. Mix with yoghurt, minced garlic, salt and pepper. Dice cucumber and fold in. Top with cheese if using. Eat cold. Genuinely good.",
    cookTime: "5 min",
  },
  {
    id: "chicken-yoghurt-bowl",
    name: "Chicken Yoghurt Bowl",
    emoji: "🍗",
    category: "protein-meals",
    summer: true,
    tags: ["high-protein"],
    cal: [250, 350], protein: [35, 45], carbs: [5, 10], fat: [5, 10], fiber: [1, 2],
    servingNote: "1 bowl",
    ingredients: ["Cooked chicken breast (100–150g)", "Curd or Greek yoghurt (100–150g)", "Garlic (2 cloves)", "Salt", "Pepper", "Cucumber (optional)"],
    recipe: "Shred or slice cooked chicken. Mix yoghurt with minced garlic, salt, pepper. Combine. Add cucumber if you want crunch. Serve cold.",
    cookTime: "10 min (if chicken pre-cooked: 5 min)",
  },
  {
    id: "tandoori-chicken",
    name: "Tandoori Chicken",
    emoji: "🍖",
    category: "protein-meals",
    summer: false,
    tags: ["high-protein", "meal-prep"],
    cal: [300, 320], protein: [40, 42], carbs: [5, 5], fat: [9, 10], fiber: [0, 1],
    servingNote: "200g chicken",
    ingredients: ["Chicken breast (200g raw)", "Kilrr marinade (20g)", "Mustard oil (1 tsp)", "Greek yoghurt (2 tbsp)"],
    recipe: "Mix marinade, mustard oil and yoghurt. Coat chicken thoroughly. Marinate minimum 2 hours, overnight is better. Grill or air-fry at 200°C for 20–25 min. Rest 5 min before eating.",
    cookTime: "25 min + marinating",
  },
  {
    id: "chicken-curry",
    name: "Chicken Curry",
    emoji: "🍛",
    category: "mains",
    summer: false,
    tags: ["high-protein", "meal-prep"],
    cal: [350, 480], protein: [50, 80], carbs: [5, 10], fat: [10, 20], fiber: [1, 2],
    servingNote: "1 serving (200–260g chicken)",
    ingredients: ["Chicken (200–260g)", "Onion (1 medium)", "Tomato (2)", "Ginger garlic paste (1 tbsp)", "Spices (cumin, coriander, garam masala, chilli)", "Oil (1 tsp)", "Salt"],
    recipe: "Sauté onion till golden. Add ginger garlic paste, cook 2 min. Add tomatoes and spices, cook till oil separates. Add chicken, coat well. Add water, cover and cook 20 min. Adjust salt.",
    cookTime: "35 min",
  },
  {
    id: "egg-curry",
    name: "Egg Curry",
    emoji: "🥚",
    category: "mains",
    summer: false,
    tags: ["vegetarian"],
    cal: [200, 300], protein: [15, 20], carbs: [5, 10], fat: [12, 18], fiber: [1, 2],
    servingNote: "2–3 eggs",
    ingredients: ["Eggoz eggs (2–3)", "Potato (optional, 1 small)", "Onion (1)", "Tomato (2)", "Spices", "Oil (1 tsp)"],
    recipe: "Hard boil eggs, peel and slit them. Make a basic onion-tomato masala. Add eggs, coat in gravy. Simmer 5 min. If using potato, cook it in the masala before adding eggs.",
    cookTime: "25 min",
  },
  {
    id: "scrambled-eggs-bread",
    name: "Scrambled Eggs + Bread",
    emoji: "🍳",
    category: "breakfast",
    summer: true,
    tags: ["quick"],
    cal: [300, 400], protein: [20, 30], carbs: [20, 25], fat: [12, 18], fiber: [2, 3],
    servingNote: "2 eggs + 2 slices",
    ingredients: ["Eggoz eggs (2–3)", "Protein bread (2 slices)", "Cheese (optional)", "Salt", "Pepper", "Butter (1 tsp)"],
    recipe: "Beat eggs with salt and pepper. Melt butter on low heat. Add eggs. Stir slowly and constantly. Remove from heat while still slightly wet — they finish cooking from residual heat. Toast bread. Plate together.",
    cookTime: "8 min",
  },
  {
    id: "rice-chicken",
    name: "Rice + Chicken",
    emoji: "🍚",
    category: "mains",
    summer: false,
    tags: ["high-protein", "meal-prep"],
    cal: [400, 700], protein: [30, 50], carbs: [50, 90], fat: [5, 15], fiber: [2, 5],
    servingNote: "1 plate",
    ingredients: ["Cooked white or brown rice (100–300g)", "Chicken (100–200g)", "Vegetables (optional)"],
    recipe: "Cook rice. Grill, air-fry or cook chicken however you prefer. Plate together. Add vegetables if you have them. Season. This is the workhorse meal.",
    cookTime: "25 min",
  },
  {
    id: "rice-eggs",
    name: "Rice + Eggs",
    emoji: "🍚",
    category: "mains",
    summer: false,
    tags: ["quick", "vegetarian"],
    cal: [350, 600], protein: [20, 30], carbs: [40, 70], fat: [10, 15], fiber: [1, 3],
    servingNote: "1 plate",
    ingredients: ["Cooked rice (100–200g)", "Eggs (2–3)", "Vegetables (optional)", "Salt", "Spices"],
    recipe: "Cook rice. Fry or scramble eggs. Plate together. That's genuinely all it needs to be.",
    cookTime: "20 min",
  },
  {
    id: "paneer-curry",
    name: "Paneer Curry",
    emoji: "🧀",
    category: "mains",
    summer: false,
    tags: ["vegetarian", "meal-prep"],
    cal: [350, 500], protein: [18, 25], carbs: [10, 15], fat: [25, 35], fiber: [1, 2],
    servingNote: "100–150g paneer",
    ingredients: ["Paneer (100–150g)", "Onion (1)", "Tomato (2)", "Spices", "Oil (1 tsp)", "Cream (optional)"],
    recipe: "Make onion-tomato masala. Add cubed paneer. Cook 5–7 min. Don't overcook paneer — it goes rubbery. Add cream at the end if you want it rich.",
    cookTime: "25 min",
  },
  {
    id: "palak-paneer",
    name: "Palak Paneer",
    emoji: "🥬",
    category: "mains",
    summer: false,
    tags: ["vegetarian", "high-fiber"],
    cal: [400, 480], protein: [20, 24], carbs: [10, 12], fat: [30, 35], fiber: [3, 5],
    servingNote: "1 bowl",
    ingredients: ["Paneer (100g)", "Spinach (2 cups)", "Onion (1)", "Garlic (3 cloves)", "Spices", "Oil (1 tsp)"],
    recipe: "Blanch spinach 2 min, blend to paste. Sauté onion and garlic. Add spices, then spinach paste. Simmer 5 min. Add paneer cubes. Cook 5 more min.",
    cookTime: "25 min",
  },
  {
    id: "paneer-chilli",
    name: "Paneer Chilli",
    emoji: "🌶️",
    category: "mains",
    summer: false,
    tags: ["vegetarian"],
    cal: [300, 400], protein: [14, 18], carbs: [10, 15], fat: [20, 28], fiber: [1, 2],
    servingNote: "1 plate",
    ingredients: ["Paneer (70–100g)", "Capsicum (1)", "Onion (1)", "Soy sauce (1 tbsp)", "Chilli sauce (1 tbsp)", "Cornflour (1 tsp)", "Oil (1 tsp)"],
    recipe: "Toss paneer cubes in cornflour, pan-fry till golden. Remove. Stir-fry capsicum and onion on high heat. Add sauces. Toss paneer back in. High heat, fast, done.",
    cookTime: "20 min",
  },
  {
    id: "jeera-rice",
    name: "Jeera Rice",
    emoji: "🍚",
    category: "sides",
    summer: false,
    tags: ["vegetarian", "quick"],
    cal: [200, 230], protein: [3, 4], carbs: [40, 45], fat: [3, 5], fiber: [1, 1],
    servingNote: "150g cooked",
    ingredients: ["Cooked rice (150g)", "Jeera (1 tsp)", "Ghee or oil (1 tsp)", "Salt"],
    recipe: "Heat ghee, add jeera and let it splutter. Add cooked rice. Toss well. Done in 3 minutes if rice is already cooked.",
    cookTime: "5 min (+ rice cooking time)",
  },
  {
    id: "greek-yoghurt-bowl",
    name: "Greek Yoghurt Bowl",
    emoji: "🥛",
    category: "snacks",
    summer: true,
    tags: ["no-cook", "quick", "vegetarian"],
    cal: [120, 200], protein: [10, 15], carbs: [10, 20], fat: [3, 5], fiber: [0, 1],
    servingNote: "1 bowl",
    ingredients: ["Greek yoghurt (150–200g)", "Honey (optional)", "Fruit (optional)"],
    recipe: "Put yoghurt in bowl. Add honey or fruit if you want. Eat. This is a snack, not a project.",
    cookTime: "1 min",
  },
  {
    id: "fruit-bowl",
    name: "Fruit Bowl",
    emoji: "🍎",
    category: "snacks",
    summer: true,
    tags: ["no-cook", "vegetarian"],
    cal: [100, 200], protein: [1, 3], carbs: [25, 40], fat: [0, 1], fiber: [3, 6],
    servingNote: "1 bowl",
    ingredients: ["Banana", "Apple", "Grapes", "Berries"],
    recipe: "Cut fruit. Put in bowl. Eat. If you need a recipe for this one, we have bigger problems.",
    cookTime: "3 min",
  },
  {
    id: "carrot-cake",
    name: "Carrot Cake",
    emoji: "🎂",
    category: "treats",
    summer: false,
    tags: ["homemade", "baked"],
    cal: [400, 450], protein: [6, 7], carbs: [45, 50], fat: [27, 29], fiber: [3, 4],
    servingNote: "per 100g slice",
    ingredients: ["All-purpose flour (300g)", "Vegetable oil (1 cup)", "Brown sugar (150g)", "White sugar (100g)", "Eggs (4)", "Carrots (300g grated)", "Pecans (75g)", "Walnuts (75g)", "Baking powder (2 tsp)", "Baking soda (1 tsp)", "Cinnamon (2 tsp)", "Nutmeg (½ tsp)", "Vanilla (1 tsp)"],
    recipe: "Mix dry ingredients. Beat eggs with sugars and oil. Combine wet and dry. Fold in carrots and nuts. Bake 180°C for 45–55 min. You know how to bake. This one's yours.",
    cookTime: "1 hour",
  },
  {
    id: "raj-kachori",
    name: "Raj Kachori",
    emoji: "🫓",
    category: "treats",
    summer: false,
    tags: ["cheat-meal"],
    cal: [450, 500], protein: [10, 12], carbs: [60, 65], fat: [20, 25], fiber: [6, 8],
    servingNote: "1 kachori",
    ingredients: ["Fried kachori shell", "Boiled potatoes", "Chana", "Curd", "Green chutney", "Tamarind chutney", "Sev"],
    recipe: "This is a chaat item. You're ordering it or buying the shell. Assemble: potato + chana in shell, top with curd, both chutneys, sev. Eat immediately before it gets soggy.",
    cookTime: "10 min assembly",
  },
  {
    id: "chicken-burger",
    name: "Chicken Burger",
    emoji: "🍔",
    category: "treats",
    summer: false,
    tags: ["cheat-meal"],
    cal: [350, 450], protein: [20, 25], carbs: [30, 40], fat: [15, 20], fiber: [1, 2],
    servingNote: "1 burger",
    ingredients: ["Chicken patty", "Burger bun", "Sauce", "Cheese", "Lettuce", "Tomato"],
    recipe: "Grill or pan-fry chicken patty. Toast bun. Assemble with sauce, cheese, vegetables. Or just order one. It's a burger.",
    cookTime: "15 min",
  },
  {
    id: "biryani",
    name: "Biryani",
    emoji: "🍲",
    category: "treats",
    summer: false,
    tags: ["cheat-meal", "order-out"],
    cal: [600, 900], protein: [20, 30], carbs: [70, 90], fat: [20, 35], fiber: [2, 4],
    servingNote: "1 plate",
    ingredients: ["Rice", "Chicken or mutton", "Oil/Ghee", "Whole spices", "Fried onions", "Saffron"],
    recipe: "You're ordering this. Track it, enjoy it, move on. Don't make it a thing.",
    cookTime: "Order: 30 min",
  },
  {
    id: "mandi",
    name: "Mandi",
    emoji: "🍖",
    category: "treats",
    summer: false,
    tags: ["order-out"],
    cal: [400, 700], protein: [20, 30], carbs: [60, 80], fat: [10, 20], fiber: [1, 2],
    servingNote: "1 plate",
    ingredients: ["Basmati rice", "Chicken", "Mild whole spices", "Oil"],
    recipe: "Order from your usual place. It's slow-cooked for hours — you're not making this at home.",
    cookTime: "Order: 30 min",
  },
  {
    id: "bun-maska",
    name: "Bun Maska",
    emoji: "🫓",
    category: "snacks",
    summer: false,
    tags: ["quick"],
    cal: [280, 300], protein: [5, 7], carbs: [35, 40], fat: [12, 14], fiber: [1, 1],
    servingNote: "1 bun",
    ingredients: ["Irani bun", "Amul butter (generous)"],
    recipe: "Slice bun. Apply butter without restraint. Eat with chai. This is non-negotiable.",
    cookTime: "2 min",
  },
  {
    id: "niloufer-chai",
    name: "Niloufer Chai",
    emoji: "🍵",
    category: "drinks",
    summer: false,
    tags: ["drink"],
    cal: [180, 200], protein: [6, 6], carbs: [20, 20], fat: [8, 9], fiber: [0, 0],
    servingNote: "1 cup",
    ingredients: ["Milk (full fat)", "Tea leaves", "Sugar"],
    recipe: "This is Hyderabad's business. You know where to get it. Track it as 190 kcal.",
    cookTime: "Go to Niloufer",
  },
  {
    id: "garlic-bread",
    name: "Garlic Bread",
    emoji: "🥖",
    category: "snacks",
    summer: false,
    tags: ["quick"],
    cal: [220, 250], protein: [6, 6], carbs: [30, 30], fat: [10, 12], fiber: [1, 1],
    servingNote: "2 slices",
    ingredients: ["Bread (2 slices)", "Butter (1 tbsp)", "Garlic (2 cloves minced)", "Parsley (optional)"],
    recipe: "Mix softened butter with minced garlic. Spread on bread. Broil or toast till golden. Eat while hot.",
    cookTime: "8 min",
  },
  {
    id: "chocolate-shake",
    name: "Chocolate Shake",
    emoji: "🍫",
    category: "drinks",
    summer: true,
    tags: ["drink", "treat"],
    cal: [300, 450], protein: [6, 10], carbs: [40, 60], fat: [10, 15], fiber: [1, 2],
    servingNote: "1 glass",
    ingredients: ["Milk (300ml)", "Chocolate syrup (2 tbsp)", "Sugar (optional)", "Ice"],
    recipe: "Blend milk, chocolate syrup, and ice. Or just shake it. Cold, sweet, done.",
    cookTime: "3 min",
  },
  {
    id: "doner-fries",
    name: "Doner Chicken Fries",
    emoji: "🍟",
    category: "treats",
    summer: false,
    tags: ["cheat-meal", "order-out"],
    cal: [400, 600], protein: [15, 20], carbs: [40, 50], fat: [20, 30], fiber: [2, 3],
    servingNote: "1 portion",
    ingredients: ["Fries", "Doner chicken", "Garlic sauce", "Chilli sauce"],
    recipe: "Order it. Track it. No guilt. Move on.",
    cookTime: "Order: 20 min",
  },
  {
    id: "chocolate-mousse",
    name: "Chocolate Mousse",
    emoji: "🍮",
    category: "treats",
    summer: true,
    tags: ["treat", "homemade"],
    cal: [300, 400], protein: [3, 5], carbs: [25, 35], fat: [20, 30], fiber: [1, 2],
    servingNote: "1 cup",
    ingredients: ["Heavy cream (100ml)", "Dark chocolate (80g)", "Sugar (2 tbsp)", "Eggs (optional)"],
    recipe: "Melt chocolate. Whip cream to soft peaks. Fold chocolate into cream gently. Refrigerate 2 hours. Eat cold.",
    cookTime: "20 min + 2 hr chill",
  },
  {
    id: "dominos-pizza",
    name: "Domino's Pizza",
    emoji: "🍕",
    category: "treats",
    summer: false,
    tags: ["cheat-meal", "order-out"],
    cal: [1000, 1100], protein: [40, 45], carbs: [120, 130], fat: [40, 45], fiber: [3, 5],
    servingNote: "4 slices (regular)",
    ingredients: ["Pizza base", "Cheese", "Chicken or corn toppings", "Sauce"],
    recipe: "Order on the app. Use the Tuesday discount. Track all 4 slices honestly.",
    cookTime: "Order: 30 min",
  },
];

export const CATEGORIES = {
  breakfast: { label: "Breakfast", emoji: "🌅" },
  "protein-meals": { label: "Protein Meals", emoji: "💪" },
  mains: { label: "Mains", emoji: "🍽️" },
  sides: { label: "Sides", emoji: "🥄" },
  snacks: { label: "Snacks", emoji: "🫙" },
  drinks: { label: "Drinks", emoji: "☕" },
  treats: { label: "Treats", emoji: "✨" },
};
